#!/bin/sh
#
# Note: this is a sample and will not be run as is.

# 影梭服务器链接
ss-local -c /etc/shadowsocks/config.json  >/dev/null 2>&1 &
# 移除空文件
rm /home/gaffey/.xsession-errors .Xauthority nemcache.sqlite
rm /home/gaffey/.pki .nv -Rf
# 自定义键盘映射
sleep 3
xmodmap /etc/X11/Xmodmap
# 连接蓝牙音箱
echo -e 'power on\nquit' | bluetoothctl&&sleep 0.5&&echo -e 'connect \t \nquit' | bluetoothctl