# kupfer
# Autogenerated from man page /usr/share/man/man1/kupfer.1.gz
complete -c kupfer -l no-splash --description 'Launch without presenting main interface.'
complete -c kupfer -l debug --description 'Enable more verbose output that can help understanding the program\\(aqs opera…'
complete -c kupfer -l list-plugins --description 'List all installed plugins by their identifier, version and description.'
complete -c kupfer -l exec-helper --description 'Run plugin helper program, which should be the name of a module inside kupfer.'
complete -c kupfer -l help --description 'Display usage information.'
complete -c kupfer -l version --description 'Display version information.'

