# nvidia-modprobe
# Autogenerated from man page /usr/share/man/man1/nvidia-modprobe.1.gz
complete -c nvidia-modprobe -s v -l version --description 'Print the utility version and exit.'
complete -c nvidia-modprobe -s h -l help --description 'Print usage information for the command line options and exit.'
complete -c nvidia-modprobe -s c -l create-nvidia-device-file --description 'Create the NVIDIA device file with the given minor number; this option can be…'
complete -c nvidia-modprobe -l module-instance --description 'option is specified on systems with multiple NVIDIA kernel modules, nvidia-mo…'
complete -c nvidia-modprobe -s i --description 'Load the required NVIDIA kernel module that corresponds to the specified  MOD…'
complete -c nvidia-modprobe -s u -l unified-memory --description 'Load the NVIDIA Unified Memory kernel module or create device files for it, i…'
complete -c nvidia-modprobe -s m -l modeset --description 'Load the NVIDIA modeset kernel module and create its device file.'

