# ss-nat
# Autogenerated from man page /usr/share/man/man1/ss-nat.1.gz
complete -c ss-nat -s s --description 'IP address of shadowsocks remote server.'
complete -c ss-nat -s l --description 'Port number of shadowsocks local server.'
complete -c ss-nat -s S --description 'IP address of shadowsocks remote UDP server.'
complete -c ss-nat -s L --description 'Port number of shadowsocks local UDP server.'
complete -c ss-nat -s i --description 'a file whose content is bypassed ip list.'
complete -c ss-nat -s a --description 'LAN IP of access control, need a prefix to define access control mode.'
complete -c ss-nat -s b --description 'WAN IP of will be bypassed.'
complete -c ss-nat -s w --description 'WAN IP of will be forwarded.'
complete -c ss-nat -s e --description 'Extra options for iptables.'
complete -c ss-nat -s o --description 'Apply the rules to the OUTPUT chain.'
complete -c ss-nat -s u --description 'Enable udprelay mode, TPROXY is required.'
complete -c ss-nat -s U --description 'Enable udprelay mode, using different IP and ports for TCP and UDP.'
complete -c ss-nat -s f --description 'Flush the rules.'
complete -c ss-nat -s h --description 'Show this help message and exit.'

