#!/bin/bash
cd /home/gaffey
sudo -u gaffey DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send 'System Backup!' '开始拷贝文件进入git项目...'
# 用户隐藏外部文件备份
rsync -av --delete .vim /home/gaffey/.config/privarcy/user/.
rsync -av --delete .w3m /home/gaffey/.config/privarcy/user/.
rsync -av --delete .ipython /home/gaffey/.config/privarcy/user/.
# 自定义配置备份
rsync -av --delete /etc/lxdm/lxdm.conf .config/privarcy/etc/.
rsync -av --delete /etc/cron.d/* .config/privarcy/etc/.
# 软件列表备份
pacman -Qqen > /home/gaffey/.config/privarcy/user/pkglist.txt
pip freeze > /home/gaffey/.config/privarcy/user/requirements.txt
sleep 1
# 提交文件至github
sudo -u gaffey DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send 'Publish Github!' '提交文件至Github服务器...'
cd /home/gaffey/.config
git add -A
git commit -m 'Daily update'
git push && sudo -u gaffey DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send 'Publish Successful!' '成功备份至Github...'
