#!/bin/bash
# 影梭服务器链接
ss-local -c ~/.config/privarcy/shadowsocks/config1.json > /dev/null 2>&1 &
cd $HOME
# 删除多余文件
#rm .xsession-errors .Xauthority nemcache.sqlite ICEauthority
#rm -Rf .pki .nv .gnupg
# 自定义键盘映射
# sleep 3
# xmodmap /etc/X11/Xmodmap
# 连接蓝牙音箱
# echo -e 'power on\nquit' | bluetoothctl&&sleep 0.5&&echo -e 'connect \t \nquit' | bluetoothctl
